### ISSUE TITLE
No work on 0.12

### ISSUE THREAD

**Issue by danielb2** [joeferner/node-oracle#254]
Works fine on 0.10 but alas ...

I don't see any other issues open on this; did I miss something?

```
Now using node v0.12.0
[daniel@nero]--(14:02:24)
[~/t/ofs]$ make install
bash: export DYLD_LIBRARY_PATH='/Users/daniel/tmp/ofs/oracle/instantclient'
fish: set -x DYLD_LIBRARY_PATH '/Users/daniel/tmp/ofs/oracle/instantclient'
npm WARN package.json ofs@1.0.0 No description
npm WARN package.json ofs@1.0.0 No repository field.
npm WARN package.json ofs@1.0.0 No README data
\
> oracle@0.3.8 install /Users/daniel/tmp/ofs/node_modules/oracle
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
In file included from ../src/connection.cpp:4:
../src/commitBaton.h:14:14: error: no member named 'Dispose' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
    callback.Dispose();
    ~~~~~~~~ ^
In file included from ../src/connection.cpp:5:
../src/rollbackBaton.h:14:14: error: no member named 'Dispose' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
    callback.Dispose();
    ~~~~~~~~ ^
../src/connection.cpp:19:53: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'uni::CallbackType (const uni::FunctionCallbackInfo &)'
```

**Comment by oebspm** [comment]
It's explained here how you should write the code for Node 0.12.
https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/

Can somebody please fix it?

**Comment by ericwaldheim** [comment]
strong-oracle runs on 0.12.  This one appears to be done.

**Comment by danielb2** [comment]
thanks @ericwaldheim ! Just what I needed. They seem compatible too so I'm just using that driver instead now. This one's dead it seems.

**Comment by danielb2** [comment]
Also looks like the docs for this driver has been updated to say as much and refers to an official oracle driver

https://github.com/oracle/node-oracledb

**Comment by raztus** [comment]
@ericwaldheim @oebspm If either of you are interested in commit access, joeferner would be more than happy to add you as a contributor. So far no one has stepped up.

#223 has not been merged because there is a conflict (perhaps minor) and I no longer have the time to invest in maintaining this driver.

**Comment by masopmac** [comment]
I have this compiling with node-gyp and running on node v4.1.2 . Might be a starting point for anyone who wants to use it. I haven't tested the new buffer code for the BLOBs but everything else seems to work.

**Comment by mrlannigan** [comment]
@masopmac I am very interested.

**Comment by cjbj** [comment]
@masopmac @mrlannigan I know you might have hard-to-migrate code bases, but what features in the other driver https://github.com/oracle/node-oracledb do you need for it to be a viable replacement?

**Comment by masopmac** [comment]
@cjbj It was the hard-to-migrate code bases as you mentioned. I haven't tested node-oracledb at all.

**Comment by mrlannigan** [comment]
@cjbj i also have a hard-to-migrate code base. But really I just need this driver to compile to node 4. I have the migration planned out, it's just I'm stuck on 0.10 until I can either get this driver compiling or moving to oracledb.

**Comment by masopmac** [comment]
Julian, I emailed you everything you need to compile it.

**Comment by cjbj** [comment]
@masopmac @mrlannigan when you get a chance to look at it, let me know your wishlist.

**Comment by mrlannigan** [comment]
@masopmac I haven't received anything?

**Comment by masopmac** [comment]
@mrlannigan sent to the email in your github profile. Let me know if there is a better place to send.
